// Stored responses from test_questions.txt + serpapi_result.txt
// Used in MOCK_MODE to replay a conversation without any API or LLM calls.

export type MockStage = "info_collection" | "budget_allocation" | "complete";

export const MOCK_REPLIES: { stage: MockStage; reply: string }[] = [
  {
    stage: "info_collection",
    reply: "Could you let me know the intended start date for your 5-day trip?",
  },
  {
    stage: "budget_allocation",
    reply:
      "I have everything I need! Here's the default budget split for your ₹40,000 INR trip:\n\n" +
      "• Transport (flights / trains / buses): 35%  (₹14,000)\n" +
      "• Accommodation: 35%  (₹14,000)\n" +
      "• Food & dining: 15%  (₹6,000)\n" +
      "• Activities & sightseeing: 10%  (₹4,000)\n" +
      "• Miscellaneous buffer: 5%  (₹2,000)\n\n" +
      "Proceed with this allocation, or tell me what you'd like to adjust.",
  },
  {
    stage: "complete",
    reply: "Here's your complete 5-day travel plan to Bhubaneswar!",
  },
];

export const MOCK_PLAN = {
  trip_overview: {
    origin: "Pune",
    destination: "Bhubaneswar",
    country: "India",
    travel_dates: { start: "2026-06-20", end: "2026-06-25", num_days: 5 },
    num_travelers: 1,
    travel_style: "comfort-budget",
    total_budget: 40000.0,
    currency: "INR",
    currency_symbol: "₹",
  },
  destination_options: [],
  recommended_destination: "Bhubaneswar",
  transport: {
    flights: {
      options: [
        {
          rank: 1,
          airline: "Air India Express",
          flight_number: "IX-1098",
          departure_time: "21:15",
          arrival_time: "23:30",
          duration: "2 hr 15 min",
          stops: "Nonstop",
          estimated_cost_per_person: 18900.0,
          total_cost: 18900.0,
          booking_platform: "Google Flights / Air India Express Website",
          booking_tips: "Book directly on the airline website to avoid extra platform convenience fees.",
        },
        {
          rank: 2,
          airline: "IndiGo",
          flight_number: "6E-6125",
          departure_time: "06:15",
          arrival_time: "12:20",
          duration: "6 hr 05 min",
          stops: "1 Stop",
          estimated_cost_per_person: 19230.0,
          total_cost: 19230.0,
          booking_platform: "Google Flights / IndiGo Portal",
          booking_tips: "Early morning flights are usually cheaper but check layover transit rules.",
        },
      ],
      recommended_rank: 1,
      total_options_found: 2,
    },
    trains: {
      options: [
        {
          rank: 1,
          train_name: "KONARK EXPRESS",
          train_number: "11019",
          operator: "Indian Railways (IRCTC)",
          departure_time: "18:00",
          arrival_time: "23:35",
          duration: "29 hr 35 min",
          class: "Sleeper Class (SL)",
          estimated_cost_per_person: 740.0,
          total_cost: 740.0,
          booking_platform: "IRCTC Official App / Website",
          booking_tips: "Most economical intercity travel option but consumes over a day of travel time.",
        },
        {
          rank: 2,
          train_name: "PUNE BBS SF EXP",
          train_number: "22881",
          operator: "Indian Railways (IRCTC)",
          departure_time: "11:20",
          arrival_time: "17:00",
          duration: "29 hr 40 min",
          class: "AC 3 Tier (3A)",
          estimated_cost_per_person: 1930.0,
          total_cost: 1930.0,
          booking_platform: "IRCTC Official Website",
          booking_tips: "AC class ensures a highly comfortable long-distance journey across states.",
        },
        {
          rank: 3,
          train_name: "KONARK EXPRESS",
          train_number: "11019",
          operator: "Indian Railways (IRCTC)",
          departure_time: "18:00",
          arrival_time: "23:35",
          duration: "29 hr 35 min",
          class: "AC 3 Tier (3A)",
          estimated_cost_per_person: 1905.0,
          total_cost: 1905.0,
          booking_platform: "ConfirmTkt App",
          booking_tips: "Runs daily, offering maximum schedule flexibility for budget commuters.",
        },
        {
          rank: 4,
          train_name: "KONARK EXPRESS",
          train_number: "11019",
          operator: "Indian Railways (IRCTC)",
          departure_time: "18:00",
          arrival_time: "23:35",
          duration: "29 hr 35 min",
          class: "AC 2 Tier (2A)",
          estimated_cost_per_person: 2725.0,
          total_cost: 2725.0,
          booking_platform: "MakeMyTrip Rail Section",
          booking_tips: "Provides higher tier comfort with curtained berths and cleaner setups.",
        },
      ],
      recommended_rank: 2,
      total_options_found: 4,
    },
    buses: {
      options: [],
      recommended_rank: 0,
      total_options_found: 0,
    },
    recommended_mode: "flight",
    recommended_operator: "Air India Express",
    recommended_cost_per_person: 18900.0,
    recommended_total_cost: 18900.0,
    local_transport: {
      daily_cost_per_person: 700.0,
      total_local_transport: 3500.0,
      recommended_options: [
        "Mo Bus public network for extremely cheap city transit",
        "Auto-rickshaws (negotiated or via Jugnoo/Ola) for point-to-point transit",
        "Pre-booked auto rentals for regional trips to Konark and Puri",
      ],
    },
    airport_transfer: {
      cost: 600.0,
      recommended_mode: "Prepaid Taxi / App Cab",
      notes: "Covers both airport-to-hotel trips at Pune and Bhubaneswar.",
    },
    total_transport_cost: 23000.0,
    within_budget: true,
    savings_tips:
      "Opt for the direct Air India Express nonstop flight to maximize sightseeing hours across a short 5-day window.",
  },
  accommodation: {
    options: [
      {
        rank: 1,
        property_name: "Hotel O Sleep Inn",
        type: "Budget Hotel",
        estimated_price_per_night: 714.0,
        total_cost: 3570.0,
        location_notes: "Centrally positioned in Bhubaneswar",
        amenities: ["Free Wi-Fi", "Air Conditioning", "Room Service"],
        booking_platform: "OYO Rooms Portal",
        breakfast_included: false,
        pro_tip: "Highly optimal for minimalist individual travelers looking for basic utility.",
      },
      {
        rank: 2,
        property_name: "Hotel O Haven Heights",
        type: "Budget Hotel",
        estimated_price_per_night: 1040.0,
        total_cost: 5200.0,
        location_notes: "Located close to commercial sightseeing belts",
        amenities: ["Air Conditioning", "Free Wi-Fi", "Daily Housekeeping"],
        booking_platform: "OYO Rooms App",
        breakfast_included: false,
        pro_tip: "Check room illumination window options during your check-in.",
      },
      {
        rank: 3,
        property_name: "Pravuprasad Homestay",
        type: "Homestay",
        estimated_price_per_night: 1035.0,
        total_cost: 5175.0,
        location_notes: "Quiet neighborhood setting",
        amenities: ["Homely Atmosphere", "Free Wi-Fi", "Luggage Storage"],
        booking_platform: "Skyscanner Hotels",
        breakfast_included: true,
        pro_tip: "Includes a reliable breakfast setup which cuts morning meal hunting time.",
      },
      {
        rank: 4,
        property_name: "Hotel Mirka Plaza",
        type: "Hotel",
        estimated_price_per_night: 1374.0,
        total_cost: 6870.0,
        location_notes: "Near transit routes",
        amenities: ["Wi-Fi", "Cable TV", "Attach Bath"],
        booking_platform: "Skyscanner / Direct Desk",
        breakfast_included: false,
        pro_tip: "Consistently rated well by individual budget sightseers.",
      },
      {
        rank: 5,
        property_name: "Hotel Golden Orchid",
        type: "Comfort Budget Hotel",
        estimated_price_per_night: 1900.0,
        total_cost: 9500.0,
        location_notes: "Jayadev Vihar primary road lane",
        amenities: ["Free Breakfast", "Wi-Fi", "In-house Restaurant", "Air Conditioning"],
        booking_platform: "HappyEasyGo / MakeMyTrip",
        breakfast_included: true,
        pro_tip: "Perfect equilibrium of comfort, premier locality, and essential amenities.",
      },
    ],
    recommended_rank: 5,
    total_options_found: 5,
    total_accommodation_cost: 9500.0,
    within_budget: true,
  },
  itinerary: {
    daily_budget_target: 700.0,
    days: [
      {
        day: 1,
        date: "2026-06-20",
        theme: "Arrival & Local Exploration",
        morning: {
          activity: "Rest from flight and check into hotel",
          location: "Hotel Golden Orchid, Jayadev Vihar",
          entry_fee: 0.0,
          notes: "Settle into your room and unpack essential sightseeing gear.",
        },
        breakfast: {
          place_type: "Hotel Restaurant",
          recommended_dish: "Complimentary South Indian Platter",
          cost: 0.0,
        },
        afternoon: {
          activity: "Explore Regional Science Centre Exhibits",
          location: "Pandav Nagar, Bhubaneswar",
          entry_fee: 30.0,
          notes: "Engaging galleries, motion simulators, and science parks.",
        },
        lunch: {
          place_type: "Local Odia Eatery",
          recommended_dish: "Odia Veg Thali with Dalma",
          cost: 180.0,
        },
        evening: {
          activity: "Relax around Bindusagar Lake",
          location: "Old Town Ward",
          entry_fee: 0.0,
          notes: "Sacred water tank encircled by ancient heritage edifices.",
        },
        dinner: {
          place_type: "Street Side Stall",
          recommended_dish: "Cuttack Dahibara Aloodum",
          cost: 90.0,
        },
        local_transport: 200.0,
        day_total: 500.0,
        budget_tip: "Utilize shared auto-rickshaws along the main avenues to keep transit costs under a dollar.",
      },
      {
        day: 2,
        date: "2026-06-21",
        theme: "Historical Architecture & Cave Wonders",
        morning: {
          activity: "Visit Udayagiri & Khandagiri Caves",
          location: "Khandagiri, Bhubaneswar",
          entry_fee: 25.0,
          notes: "Ancient rock-cut Jain monastic chambers dating to the 2nd century BCE.",
        },
        breakfast: {
          place_type: "Hotel Restaurant",
          recommended_dish: "Puri Sabzi & Masala Chai",
          cost: 0.0,
        },
        afternoon: {
          activity: "Tour the Odisha State Museum",
          location: "Kalpana Square, Bhubaneswar",
          entry_fee: 50.0,
          notes: "Exceptional collection of palm-leaf manuscripts and folk arts.",
        },
        lunch: {
          place_type: "Budget Restaurant",
          recommended_dish: "Chhena Poda dessert & Meals",
          cost: 220.0,
        },
        evening: {
          activity: "Walk through Ekamra Kanan Botanical Gardens",
          location: "Nayapalli, Bhubaneswar",
          entry_fee: 30.0,
          notes: "Expansive green lung featuring a cactus house and serene lake.",
        },
        dinner: {
          place_type: "Casual Diner",
          recommended_dish: "Chhena Jhili & Roti with Curry",
          cost: 150.0,
        },
        local_transport: 225.0,
        day_total: 700.0,
        budget_tip: "Purchase entry tickets directly at digital ASI counters to skip queue premium charges.",
      },
      {
        day: 3,
        date: "2026-06-22",
        theme: "Day Trip to Globally Renowned Sun Temple",
        morning: {
          activity: "Travel and explore Konark Sun Temple (35 km regional transit)",
          location: "Konark, Odisha",
          entry_fee: 40.0,
          notes: "13th-century monumental chariot temple structure, a UNESCO World Heritage site.",
        },
        breakfast: {
          place_type: "Hotel Restaurant",
          recommended_dish: "Idli-Vada Combo",
          cost: 0.0,
        },
        afternoon: {
          activity: "Relax at Chandrabhaga Beach",
          location: "Konark Coastline",
          entry_fee: 0.0,
          notes: "Clean coastal stretch situated right near the temple monument compound.",
        },
        lunch: {
          place_type: "Beachside Shack",
          recommended_dish: "Fresh Coastal Fish Curry with Rice",
          cost: 250.0,
        },
        evening: {
          activity: "Walk around the ASI Museum compound",
          location: "Konark Temple Environs",
          entry_fee: 10.0,
          notes: "Preserves recovered structural sculptures and architectural fragments.",
        },
        dinner: {
          place_type: "Highway Dhaba",
          recommended_dish: "Tandoori Roti with Tadka",
          cost: 150.0,
        },
        local_transport: 850.0,
        day_total: 1300.0,
        budget_tip: "Take OSRTC state buses running between Bhubaneswar and Konark to save heavily compared to private cabs.",
      },
      {
        day: 4,
        date: "2026-06-23",
        theme: "Ancient Temples & Peace Pagoda",
        morning: {
          activity: "Architectural study of Lingaraj & Mukteshvara Temples",
          location: "Old Town, Bhubaneswar",
          entry_fee: 0.0,
          notes: "Marvelous Kalinga-style architectural stone towers with intricate reliefs.",
        },
        breakfast: {
          place_type: "Hotel Restaurant",
          recommended_dish: "Upma and Ghuguni",
          cost: 0.0,
        },
        afternoon: {
          activity: "Excursion to Dhauli Shanti Stupa",
          location: "Dhauli Hills (8 km from city)",
          entry_fee: 0.0,
          notes: "White peace pagoda marking Emperor Ashoka's historical path change.",
        },
        lunch: {
          place_type: "Highway Restaurant",
          recommended_dish: "Standard North Indian Veg Thali",
          cost: 200.0,
        },
        evening: {
          activity: "Shopping for handicrafts at Ekamra Haat",
          location: "Madusudan Nagar, Bhubaneswar",
          entry_fee: 5.0,
          notes: "Folk arts marketplace showcasing beautiful Pattachitra paintings.",
        },
        dinner: {
          place_type: "Market Food Stall",
          recommended_dish: "Mutton / Veg Roll and sweets",
          cost: 165.0,
        },
        local_transport: 330.0,
        day_total: 700.0,
        budget_tip: "Non-Hindus can view Lingaraj inner compound clearly from the raised platform structure for free.",
      },
      {
        day: 5,
        date: "2026-06-24",
        theme: "Wildlife Exploration & Departure Prep",
        morning: {
          activity: "Safari trail at Nandankanan Zoological Park",
          location: "Barang Road, Bhubaneswar",
          entry_fee: 50.0,
          notes: "Renowned sanctuary setting famous for its rare white tigers.",
        },
        breakfast: {
          place_type: "Hotel Restaurant",
          recommended_dish: "Poha and Filter Coffee",
          cost: 0.0,
        },
        afternoon: {
          activity: "Stroll around Kanjia Lake wetlands",
          location: "Nandankanan Compound",
          entry_fee: 25.0,
          notes: "Serene wetland ecosystem offering budget boating activities.",
        },
        lunch: {
          place_type: "Zoo Cafeteria",
          recommended_dish: "Fried Rice with Manchurian",
          cost: 180.0,
        },
        evening: {
          activity: "Pack bags and execute hotel check-out process",
          location: "Hotel Golden Orchid",
          entry_fee: 0.0,
          notes: "Prepare travel documents for your late night return journey.",
        },
        dinner: {
          place_type: "Airport Food Counter",
          recommended_dish: "Sandwich and Juice Combo",
          cost: 245.0,
        },
        local_transport: 300.0,
        day_total: 800.0,
        budget_tip: "Take the Mo Bus route network to the airport gate terminal for maximum savings.",
      },
    ],
    total_food_and_activities: 2200.0,
    free_time_suggestions: [
      "Stroll the green walking loops around Nicco Park areas",
      "Observe stone sculptors at work near the old town alley paths",
    ],
    money_saving_hacks: [
      "Use public Mo Bus transit routes across prominent junctions",
      "Enjoy the free complimentary hotel breakfasts to eliminate morning costs",
    ],
  },
  budget_summary: {
    total_budget: 40000.0,
    breakdown: {
      flights_and_intercity_transport: 18900.0,
      local_transport: 3500.0,
      airport_transfers: 600.0,
      accommodation: 9500.0,
      food: 1810.0,
      activities: 390.0,
      emergency_buffer_10pct: 4000.0,
    },
    total_estimated_cost: 38700.0,
    remaining_buffer: 1300.0,
    status: "TIGHT_FIT" as const,
    verdict:
      "The comfort-budget plan successfully utilizes direct flight travel and premium mid-range budget lodging while safely securing a 10% emergency buffer, making it a tight but highly robust fit.",
    top_savings_opportunities: [
      "Switch from premium comfort hotel choice to basic rank 1 OYO rooms to save roughly 5,930 INR",
      "Substitute flight tickets with AC 3-Tier train choices to trim transport expenditure by over 15,000 INR",
      "Stick strictly to city-administered Mo Bus routes instead of private auto rentals for long distances",
    ],
  },
};
